name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  mobile_scanner: ^3.5.5  # Replaced qr_code_scanner with mobile_scanner
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
